Ajout projet et modification en hook pour les call apollo
SocialGouv/TextStyle pull request #2
Opened 2019-11-02 14:39 UTC by Taloud

2019-11-05 09:31 UTC, kwiss approved these changes

2019-11-05 09:31 UTC, kwiss commented on app/components/Articles/EditArticle.js
> +const DELETE_ARTICLE = gql`
les const de query/mutation sont a bouger dans un fichier correspondant

2019-11-05 09:31 UTC, kwiss commented on app/components/Articles/EditArticle.js
> +        </form>
strange indent do you use eslint ?

2019-11-05 09:31 UTC, kwiss commented on app/components/Articles/PaginationArticle.js
> +              pathname: '/project/'+ projectId,
?? `/project/${projectId}`

2019-11-05 09:31 UTC, kwiss commented on app/components/PageLayout.js
> +
😔

2019-11-05 09:31 UTC, kwiss commented on app/components/Projects/AddProject.js
> +  const [addProject, { data }] = useMutation(ADD_PROJECT);
data ?

2019-11-05 09:31 UTC, kwiss commented on app/components/Research/ElasticResearch.js
> +                    }
move that function

2019-11-05 09:31 UTC, kwiss commented on app/components/Research/ElasticResearch.js
> +                        }
move that in another forlder

2019-11-05 09:33 UTC, kwiss commented
globally, there is a problem with indent you should use eslint https://github.com/SocialGouv/linters

2019-11-05 09:33 UTC, kwiss requested changes
check indent, console.log etc for merge

2019-11-06 08:49 UTC, kwiss commented on app/.eslintrc.json
> +    "extends": "eslint:recommended",
you should use https://github.com/SocialGouv/linters

2019-11-06 08:50 UTC, kwiss commented on app/components/Research/ElasticResearch.js
> +        "size": 5, "_source": { "includes": ["*"], "excludes": [] }, "from": 0
indent is really strange

2019-11-06 11:09 UTC, revolunet commented on app/components/Articles/PaginationArticle.js
> +              pathname: '/project/'+ projectId,
template literals FTW !

2019-11-06 11:10 UTC, revolunet commented
Hugo, je t'invite à relire la doc sur les commits conventionnels : https://www.conventionalcommits.org

voir aussi la PR sur les linters et bootstrap

2019-12-03 13:20 UTC, merged